plugins {
    id 'base'
}
dependencies {

}

tasks.register('compileApp', Exec) {
    group = 'build'
    description = 'Compiles the ArcCpp launcher using g++'

    inputs.dir(projectDir)
    inputs.dir(file("../idea"))
    outputs.file(file("$projectDir/app"))

    workingDir = projectDir

    commandLine 'sh', '-c', """
    ulimit -v 980000 && \\
    g++ -std=c++20 -g  -fsanitize=address -I..  \\
    ../idea/MlogI.cpp util/Log.cpp util/OS.cpp audio/Soloud.cpp Events.cpp util/Threads.cpp \\
    -L.  -lSDL2 -lpthread \\
    -Wl,-rpath,. -o app
"""}

tasks.register('run', Exec) {
    group = 'run'
    description = 'Runs the compiled launcher'
    dependsOn 'compileApp'
    
    workingDir = projectDir
    commandLine './app'
}

tasks.named('assemble') {
    dependsOn 'compileApp'
}
